### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by art-ortega**
Attempting to parse `Strippoli, Charles J (HM Home and Community Svcs LLC)` would  bug out in an else if condition, nameParts doesn't exist within the scope of this `else if` block - it has to be updated to namePartWords

Input: `Strippoli, Charles J (HM Home and Community Svcs LLC)`
Expected Output: 
```
{
  title: '',
  first: 'Charles',
  middle: 'J',
  last: 'Strippoli',
  nick: 'HM Home and Community Svcs LLC',
  suffix: '',
  error: []
}
```

### CODE REVIEW

**Comment by danielzev** [comment]
any updates on getting this in?

**Comment by chris-pardy** [comment]
> any updates on getting this in?

Sorry, didn't see the notification on this PR. I'll review by EOD today.

**Review by chris-pardy — CHANGES_REQUESTED** [review]
@art-ortega or @danielzev could you provide documentation regarding the issue you're trying to solve, ideally with a test case and an automated test?

For documentation an input and expected output is fine. Alternatively please update the original issue and reference it in this PR.

**Review by chris-pardy — APPROVED** [review]
Looks good!

**Comment by danielzev** [comment]
thanks @chris-pardy! looking forward to us pointing back to your source repo!

**Comment by chris-pardy** [comment]
@danielzev thanks and sorry for the delay. In getting a review done. I'm working on bringing the config files in this repo up-to-par so issues and prs like this won't be auto assigned.

**Pull request merged**
